title: 'Enfield Docs'
theme: 'theme/'
pages:
    - What is Enfield?: 'docs/home.md'
    - Quick Start: 'docs/quick-start.md'
    - Setup & Usage:
        - Command Line Options: 'docs/cli-options.md'
        - Configuration: 'docs/config.md'
    - Themes:
        - Creating A Theme: 'docs/creating-a-theme.md'
        - Template Variables: 'docs/template-variables.md'
