# The title of your site
title: 'Hoxton'

# This is the theme which species where the template for your site/docs.
theme: 'theme/'

# This is the base_url because we are publishing this to: http://mattvagni.github.io/hoxton-docs/
base_url: '/hoxton-docs/'

# These are the pages in the order and section's you'd like.
pages:
    - Introduction: 'docs/introduction.md'
    - Quick Start: 'docs/quick-start.md'
    - Setup & Usage:
        - Configuration: 'docs/configuration.md'
        - Command Line Options: 'docs/cli-options.md'
    - Themes:
        - Creating A Theme: 'docs/creating-a-theme.md'
        - Template Variables: 'docs/template-variables.md'

# This is a list of files or folders you'd like to manually include in your build.
include:
    - favicon.ico
    - downloads/
